[package]
name = "fixapi"
version = "0.1.0"
edition = "2024"

[dependencies]
rig-core = { version = "0.11.1", features = ["all"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
